### ISSUE TITLE
Bug de API

### ISSUE THREAD

**Issue by LaiLestrange** [TreinaDev/pague-aluguel#137]
Reproduzindo o erro:
 -  último commit na main de pague_aluguel: commit [9aa3b5a3ce054c116fbddf8c57f8e7654207052d](https://github.com/TreinaDev/pague-aluguel/commit/9aa3b5a3ce054c116fbddf8c57f8e7654207052d)
 - nenhuma api ligada

No terminal:
rake spec

O que está acontecendo:
![Image](https://github.com/user-attachments/assets/5c2d0577-ec97-42b6-9db4-4a85f01d0197)
![Image](https://github.com/user-attachments/assets/e62ebea6-48bf-43a4-a34d-50b254262cd8)

Possível solução: provavelmente mockar o que tiver falhando nos testes em questão deve resolver.

**Comment by zutin** [comment]
Não consegui replicar o erro, rodei com o commit 9aa3b5a como informado e usando `rake spec`, sem nenhuma outra aplicação rodando, tudo funcionando normal.

![Image](https://github.com/user-attachments/assets/5091c20a-bfe9-455e-acb7-287813387316)

Também rodei o teste informado `Administrador acessa página do condomínio (/spec/system/condos/admin_access_condo_managing_page_spec.rb) - e vê dashboard do admin (linha 42)` com `rspec` e não consegui replicar esse erro.

![Image](https://github.com/user-attachments/assets/1eb6b28e-bf71-4ec0-83fb-f3473db7b288)

**Comment by LaiLestrange** [comment]
Boa, Gian! Deve ter sido problema de usuária então hehe, rodei aqui e ta tudo funcionando agora, é o que importa kk Vou fechar esse issue. Valeu.
