### ISSUE TITLE
Erro ao criar uma Cobrança Avulsa (`SingleCharge`)

### ISSUE THREAD

**Issue by NathanaelV** [TreinaDev/pague-aluguel#94]
Ao preencher o formulário de **cobrança avulsa** e depois de clicar em cadastrar temos o seguinte erro.

![image](https://github.com/user-attachments/assets/fa6e384d-4bf0-436a-ab21-c5311e4261c3)

![image](https://github.com/user-attachments/assets/422eb2ea-5a3f-47a8-85d0-8e2f1e3a34de)

Ao tentar acessar a listagem de **cobranças avulsas** pelo link http://localhost:4000/condos/8/single_charges/new, temos o seguinte erro:

![image](https://github.com/user-attachments/assets/c1401875-e1cd-4883-bfc3-e465220643e1)

Após tentar cadastrar uma cobrança avulsa, não é mais possível acessar o show do Condomínio. 

![image](https://github.com/user-attachments/assets/4a4f6301-93a9-4ea3-8be5-e11da82e9304)

**Comment by zutin** [comment]
Corrigido no PR #92, com a aprovação já pode fechar o issue

https://github.com/TreinaDev/pague-aluguel/pull/92
